# Generated by Django 5.0.6 on 2024-06-24 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Unknown Company', max_length=100, verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='Month')),
                ('highest_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Highest Price')),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lowest Price')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Open Price')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Close Price')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Monthly_Prices', to='stock_App.stockprice')),
            ],
        ),
    ]
